-- Create Regions table
CREATE TABLE IF NOT EXISTS Regions (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Create Cities table
CREATE TABLE IF NOT EXISTS Cities (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    RegionId INT,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (RegionId) REFERENCES Regions(id)
);

-- Create Users table
CREATE TABLE IF NOT EXISTS Users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    cin VARCHAR(255) NOT NULL UNIQUE,
    fullName VARCHAR(255) NOT NULL,
    phoneNumber VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    RegionId INT,
    CityId INT,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (RegionId) REFERENCES Regions(id),
    FOREIGN KEY (CityId) REFERENCES Cities(id)
);

-- Create Agencies table
CREATE TABLE IF NOT EXISTS Agencies (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    legalInfo JSON NOT NULL,
    workDomain VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    CityId INT,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (CityId) REFERENCES Cities(id)
);

-- Create Agencies table
CREATE TABLE IF NOT EXISTS Agencies (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    address VARCHAR(255),
    phone VARCHAR(20),
    email VARCHAR(255),
    CityId INT,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (CityId) REFERENCES Cities(id)
);

-- Create AgencyProblemTypes table (junction table)
CREATE TABLE IF NOT EXISTS AgencyProblemTypes (
    id INT PRIMARY KEY AUTO_INCREMENT,
    AgencyId INT,
    problemType VARCHAR(255) NOT NULL,
    FOREIGN KEY (AgencyId) REFERENCES Agencies(id)
);

-- Create Reports table
CREATE TABLE IF NOT EXISTS Reports (
    id INT PRIMARY KEY AUTO_INCREMENT,
    dangerType VARCHAR(255),
    problemType VARCHAR(255) NOT NULL,
    images JSON NOT NULL,
    location JSON NOT NULL,
    status ENUM('pending', 'in_progress', 'resolved') DEFAULT 'pending',
    priority ENUM('low', 'medium', 'high') DEFAULT 'medium',
    UserId INT,
    CityId INT,
    AgencyId INT,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (UserId) REFERENCES Users(id),
    FOREIGN KEY (CityId) REFERENCES Cities(id),
    FOREIGN KEY (AgencyId) REFERENCES Agencies(id)
);